const SET_LOADING_STATUS = "SET_LOADING_STATUS";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const SET_ACCOUNT_RS = "SET_ACCOUNT_RS";
const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_AUCTIONS = "FETCH_AUCTIONS";
const FETCH_PAGES = "FETCH_PAGES";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export {
  SET_LOADING_STATUS,
  SET_CURRENT_USER,
  SET_ACCOUNT_RS,
  FETCH_PRODUCTS,
  FETCH_PAGES,
  SEARCH_PRODUCT,
  FETCH_AUCTIONS,
};
